export const sample_foods: any[] = [
  {
    id: "1",
    name: "Vegetables Pizza",
    price: 9,
    tags: ["FastFood", "Pizza", "Lunch"],
    favorite: false,
    stars: 4.0,
    imageUrl: "assets/food-1.jpg",
    origins: ["india", "asia"],
    cookTime: "40-50",
  },
  {
    id: "2",
    name: "Burger",
    price: 6,
    tags: ["FastFood", "Burger", "Lunch"],
    favorite: true,
    stars: 4.5,
    imageUrl: "assets/food-2.jpg",
    origins: ["america"],
    cookTime: "20-25",
  },
  {
    id: "3",
    name: "Pasta Carbonara",
    price: 12,
    tags: ["Italian", "Pasta", "Dinner"],
    favorite: true,
    stars: 4.8,
    imageUrl: "assets/food-3.jpg",
    origins: ["italy"],
    cookTime: "25-30",
  },
  {
    id: "4",
    name: "Sushi Platter",
    price: 18,
    tags: ["Japanese", "Sushi", "Lunch", "Dinner"],
    favorite: false,
    stars: 4.2,
    imageUrl: "assets/food-4.jpg",
    origins: ["japan", "asia"],
    cookTime: "30-40",
  },
  {
    id: "5",
    name: "Chicken Tikka Masala",
    price: 11,
    tags: ["Indian", "Chicken", "Dinner"],
    favorite: true,
    stars: 4.7,
    imageUrl: "assets/food-5.jpg",
    origins: ["india"],
    cookTime: "35-45",
  },
  {
    id: "6",
    name: "Steak",
    price: 20,
    tags: ["American", "Beef", "Dinner"],
    favorite: true,
    stars: 4.6,
    imageUrl: "assets/food-7.jpg",
    origins: ["america"],
    cookTime: "25-35",
  },
  {
    id: "7",
    name: "Miso Soup",
    price: 4,
    tags: ["Japanese", "Soup", "Starter"],
    favorite: false,
    stars: 4.3,
    imageUrl: "assets/food-8.jpg",
    origins: ["japan", "asia"],
    cookTime: "15-20",
  },
  {
    id: "8",
    name: "Caesar Salad",
    price: 8,
    tags: ["American", "Salad", "Starter"],
    favorite: false,
    stars: 4.1,
    imageUrl: "assets/food-9.jpg",
    origins: ["italy", "america"],
    cookTime: "10-15",
  },
  {
    id: "9",
    name: "Pad Thai",
    price: 10,
    tags: ["Thai", "Noodles", "Lunch", "Dinner"],
    favorite: true,
    stars: 4.9,
    imageUrl: "assets/food-10.jpg",
    origins: ["thailand", "asia"],
    cookTime: "20-30",
  },
  {
    id: "10",
    name: "Tacos",
    price: 7,
    tags: ["Mexican", "Tacos", "Lunch", "Dinner"],
    favorite: false,
    stars: 4.4,
    imageUrl: "assets/food-11.jpg",
    origins: ["mexico"],
    cookTime: "15-20",
  },
];

export const sample_tags: any[] = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];
